---
- name: Packer build MongoDB image
  hosts: all
  become: true
  vars:
    date: "{{ lookup('pipe', 'date +%Y%m%d-%H%M') }}"
  tasks:
  - name: Role DB
    include_role:
       name: dbj
  - name: Set build Date in /root/build_date
    lineinfile:
      path: /root/build_date
      create: yes
      line: "{{ date }}"
