---
- name: Packer build App image
  hosts: all
  become: true
  gather_facts: false
  vars:
    date: "{{ lookup('pipe', 'date +%Y%m%d-%H%M') }}"
#  roles:
#  - { role: app, tags: [ 'ruby' ] }
  tasks:
  - include: ../roles/app/tasks/main.yml
## Так теги в роли не пробрасываются
### https://github.com/ansible/ansible-modules-core/issues/5077
### https://github.com/ansible/ansible/issues/34196
##  - name: Role app
##    include_role:
##       name: app
###    tags:
###      - always
###      - ruby
  - name: Set build Date in /root/build_date
    lineinfile:
      path: /root/build_date
      create: yes
      line: "{{ date }}"
    tags:
      - build-date
